Feature: User Registration Service Tests 

Background: Server is up and running 
Given Rest service is deployed on "http://demo4963299.mockable.io/"

Scenario: Verify if new user is registered successfully with all input fields 
When I registered an user on "/user/1" with "Header_with_all_mandatory_fields"
Then I should get response as "success_response" and status code as "200"

Scenario: Verify if new user is registered successful with all mandatory fields but without optional fields 
When I registered an user on "/user/2" with "Header_with_out_optional_fields"
Then I should get response as "success_response_with_autogenerated_login_name" and status code as "200"

Scenario: Verify failed user registration when system generated login-name was already exists 
When I registered an user on "/user/3" with "Header_with_duplicate_login_name"
Then I should get response as "error_duplicate_login_name" and status code as "403"

Scenario: Verify failed user registration if user is missing mandatory field 
When I registered an user on "/user/4" with "Header_with_missing_mandatory_fields"
Then I should get response as "error_missing_mandatory_field" and status code as "400"

Scenario: Verify if user is trying to register when he/she is already registered  
When I registered an user on "/user/5" with "Header_with_user_already_exist"
Then I should get response as "error_duplicate_login_name" and status code as "403"
